# Generated by Django 5.2.8 on 2025-11-26 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransporteApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                (
                    "logo",
                    models.ImageField(default="logos/default.png", upload_to="logos/"),
                ),
                (
                    "precio_base",
                    models.DecimalField(decimal_places=2, default=3000, max_digits=8),
                ),
                (
                    "costo_por_km",
                    models.DecimalField(decimal_places=2, default=800, max_digits=8),
                ),
                (
                    "costo_por_min",
                    models.DecimalField(decimal_places=2, default=100, max_digits=10),
                ),
                (
                    "factor_dinamico",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
                ),
                ("tiempo_espera", models.IntegerField(default=5)),
                (
                    "link_base",
                    models.CharField(
                        default="https://www.google.com",
                        help_text="URL a la que se redirige al usuario para solicitar el viaje.",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "verbose_name": "Aplicación de Transporte",
            },
        ),
        migrations.CreateModel(
            name="Ruta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origen", models.CharField(max_length=100)),
                ("destino", models.CharField(max_length=100)),
                ("distancia_km", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "tiempo_min",
                    models.IntegerField(help_text="Tiempo estimado en minutos"),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ruta Disponible",
                "ordering": ["origen", "destino"],
                "unique_together": {("origen", "destino")},
            },
        ),
        migrations.CreateModel(
            name="CotizacionTraslado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tiempo_espera", models.IntegerField(null=True)),
                (
                    "factor_dinamico",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ruta",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cotizador.ruta",
                    ),
                ),
                (
                    "app_seleccionada",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cotizador.transporteapp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Cotizacion",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
