# Generated by Django 5.2.8 on 2025-11-16 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporteApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('tarifa_base', models.DecimalField(decimal_places=2, default=3000, max_digits=5)),
                ('costo_por_km', models.DecimalField(decimal_places=2, default=800, max_digits=5)),
                ('max_multiplicador', models.DecimalField(decimal_places=2, default=1.5, max_digits=3)),
            ],
            options={
                'verbose_name': 'Aplicación de Transporte',
            },
        ),
        migrations.CreateModel(
            name='SolicitudTraslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_nombre', models.CharField(max_length=100)),
                ('destino_nombre', models.CharField(max_length=100)),
                ('app_seleccionada', models.CharField(max_length=50)),
                ('precio_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Traslado',
            },
        ),
    ]
