# Generated by Django 5.2.8 on 2025-11-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteapp',
            name='logo_filename',
            field=models.CharField(default='default.png', help_text='Nombre del archivo del logo (ej: uber.png) en static/img/', max_length=50),
        ),
    ]
