# Generated by Django 5.2.8 on 2025-11-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0002_transporteapp_logo_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporteapp',
            name='costo_por_km',
            field=models.DecimalField(decimal_places=2, default=800, max_digits=6),
        ),
        migrations.AlterField(
            model_name='transporteapp',
            name='tarifa_base',
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=6),
        ),
    ]
