# Generated by Django 5.2.8 on 2025-11-16 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0003_alter_transporteapp_costo_por_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudtraslado',
            name='app_seleccionada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizador.transporteapp'),
        ),
    ]
