# Generated by Django 5.2.8 on 2025-11-22 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0004_alter_solicitudtraslado_app_seleccionada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudtraslado',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Solicitud de Traslado'},
        ),
        migrations.RemoveField(
            model_name='transporteapp',
            name='logo_filename',
        ),
        migrations.AddField(
            model_name='solicitudtraslado',
            name='factor_dinamico',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtraslado',
            name='tiempo_espera',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transporteapp',
            name='link_base',
            field=models.CharField(default='https://www.google.com', help_text='URL a la que se redirige al usuario para solicitar el viaje.', max_length=200),
        ),
        migrations.AddField(
            model_name='transporteapp',
            name='logo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transporteapp',
            name='costo_por_km',
            field=models.DecimalField(decimal_places=2, default=800, max_digits=8),
        ),
        migrations.AlterField(
            model_name='transporteapp',
            name='tarifa_base',
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=8),
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tiempo_min', models.IntegerField(help_text='Tiempo estimado en minutos')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ruta Disponible',
                'ordering': ['origen', 'destino'],
                'unique_together': {('origen', 'destino')},
            },
        ),
    ]
