# Generated by Django 5.2.8 on 2025-11-22 12:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0005_alter_solicitudtraslado_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolicitudTraslado',
            new_name='CotizacionTraslado',
        ),
        migrations.AlterModelOptions(
            name='cotizaciontraslado',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Solicitud de Cotizacion'},
        ),
        migrations.RenameField(
            model_name='cotizaciontraslado',
            old_name='precio_estimado',
            new_name='precio',
        ),
    ]
