# Generated by Django 5.2.8 on 2025-11-22 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0006_rename_solicitudtraslado_cotizaciontraslado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciontraslado',
            name='ruta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizador.ruta'),
        ),
        migrations.AlterField(
            model_name='cotizaciontraslado',
            name='factor_dinamico',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='transporteapp',
            name='logo',
            field=models.CharField(default='default.png', max_length=255),
        ),
    ]
