# Generated by Django 5.2.8 on 2025-11-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0007_cotizaciontraslado_ruta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporteapp',
            name='logo',
            field=models.ImageField(default='logos/default.png', upload_to='logos/'),
        ),
    ]
